### ISSUE TITLE
Code: 47. DB::Exception: Unknown column with materialized columns in joins

### ISSUE THREAD

**Issue by AaronLhiu** [ClickHouse/metabase-clickhouse-driver#260]
This bug mentioned before:
https://github.com/ClickHouse/ClickHouse/issues/41964

Now it occurs again in Metabase connecting to Clickhouse.

**Comment by slvrtrn** [comment]
> Proven to be fixed by Analyzer.
> This issue is waiting when the Analyzer will be enabled by default.

The driver sets `allow_experimental_analyzer=0` currently because of https://github.com/ClickHouse/ClickHouse/issues/64487 (which is now closed); on the previous CH versions, a lot of tests from the Metabase test suite were red because of that.

Re-enabling it could probably help in this case; we need to check if the Metabase test suite will pass with the analyzer enabled.

**Comment by slvrtrn** [comment]
@AaronLhiu, could you try with https://github.com/ClickHouse/metabase-clickhouse-driver/releases/tag/1.50.3?

NB: keep in mind that https://github.com/ClickHouse/ClickHouse/issues/64487 was fixed only in 24.7.

**Comment by AaronLhiu** [comment]
Yes, it's working for the new driver.
Thanks that fix this issue so quickly.
